# Generated by Django 5.1.6 on 2025-02-15 22:00

from django.db import migrations

def create_default_category(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    if not Category.objects.filter(name="Uncategorized").exists():
        Category.objects.create(name="Uncategorized", slug="uncategorized")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_category),
    ]
